### ISSUE TITLE
Timeshift not triggerd by influxdb

### ISSUE THREAD

**Issue by nielsdeb** [thedrhax-dockerfiles/influxdb-timeshift-proxy#1]
I wanted to add this docker container to a platform named Mainflux that I'm testing at the moment using docker-compose. I'm able to start influxdb-timeshift-proxy without errors, but when I go into Grafana (v5.3.4) and add an alias to shift a query, nothing happens. I assume that the influxdb-timeshift-proxy is not being triggerd by influxdb when Grafana asks for a query. Or am I missing something else?

This is a query that I want to shift 1 week (shows the same graph with or without the alias):
`
SELECT "Value" AS "shift_1_weeks" FROM "autogen"."messages" WHERE ("Unit" = 'Cel') AND $timeFilter
`

These are the important parts of the docker-compose file:
```yml
influxdb:
    image: influxdb:1.5.2-alpine
    container_name: mainflux-influxdb
    restart: on-failure
    environment:
      INFLUXDB_DB: db_name
      INFLUXDB_ADMIN_USER: user
      INFLUXDB_ADMIN_PASSWORD: pw
    networks:
      - docker_mainflux-base-net
  influxdb-timeshift-proxy:
    tty: true
    stdin_open: true
    image: thedrhax/influxdb-timeshift-proxy:latest
    container_name: timeshift
    depends_on:
      - influxdb
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      #tried INFLUXDB=influxdb:8086 aswell
      - INFLUXDB=mainflux-influxdb:8086
    networks:
      - docker_mainflux-base-net
```

The timeshift docker-container show the following container logs:
```
influxdb-timeshift-proxy@0.0.8 start /influxdb-timeshift-proxy
node ./bin/www
```
